### ISSUE TITLE
suggestion: allow flash of resources zip files

### ISSUE THREAD

**Issue by Albirew** [ZephyrLabs/PinetimeFlasher#11]
Is it possible to update app to allow flash of resources zip files that comes with latest version of infinitime?

**Comment by ZephyrLabs** [comment]
Hi @Albirew I haven't been looking over the project in a while as it was just supposed to be a basic app to simplify flashing the firmware.

Flashing the resources is out of the scope of OpenOCD here, and it will most likely not be included anytime soon.
